title: Web Components for Scientific Visualisation
description: Documentation for web components for scientific visualisation
theme: just-the-docs
baseurl: /scientific-visuals/
url: https://digital-precision-health.github.io

aux_links:
  source codes: https://github.com/digital-precision-health/scientific-visuals
callouts:
  note:    
    color: yellow