title: Web Components for Scientific Visualisation
description: Documentation for web components for scientific visualisation
theme: just-the-docs

url: https://digital-precision-helath.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template